In [28]:
from IPython import get_ipython
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [30]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD
import numpy as np
from sklearn.preprocessing import OneHotEncoder
import keras_test as kt

In [33]:
reload(utils)
reload(kt)

<module 'keras_test' from 'keras_test.pyc'>

In [18]:
X, y = kt.read_data(threshold=5)

input matrix of shape: (6449, 682230)
output matrix of shape: (6449, 3846)
[[ 0.          0.18545511]
 [ 1.          0.12823694]
 [ 2.          0.33354008]
 [ 3.          0.15971468]
 [ 4.          0.08032253]
 [ 5.          0.11273066]]


In [19]:
def one_hot(y):
    """
    one hot encode the target variables
    :param y: a 1d numpy array
    :return: a [n_data, 10] numpy array
    """
    enc = OneHotEncoder(n_values=10, sparse=False)
    temp = enc.fit_transform(y)
    return np.reshape(temp, newshape=[-1, 10], order='C')

In [20]:
model = Sequential()
input_dim = features.shape[1]
model.add(Dense(output_dim=128, input_dim=input_dim))
model.add(Activation("relu"))
model.add(Dense(output_dim=10))
model.add(Activation("softmax"))

model.compile(loss="categorical_crossentropy", optimizer=SGD(lr=0.01, momentum=0.9, nesterov=True),
              metrics=['accuracy'])

In [34]:
km = kt.keras_model(model, batch_size=32, training_epochs=1)
y_preds = utils.run_cv_pred(X, y, n_folds=2, model=km)
utils.get_metrics(y, y_preds)

/Users/benchamberlain/anaconda/envs/tensorflow/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


Epoch 1/1
3226/3226 [==============================] - 1s     
Epoch 1/1
 256/3226 [=>............................] - ETA: 2s - loss: 1.7353 - acc: 0.3164

/Users/benchamberlain/anaconda/envs/tensorflow/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


3223/3223 [==============================] - 0s     
macro
0.112323897711
micro
0.348271049775
all
[ 0.16604893  0.          0.50515098  0.          0.          0.00274348]


/Users/benchamberlain/anaconda/envs/tensorflow/lib/python2.7/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [35]:
km = kt.keras_model(model, batch_size=32, training_epochs=3)
y_preds = utils.run_cv_pred(X, y, n_folds=2, model=km)
utils.get_metrics(y, y_preds)

t1
Epoch 1/3
 160/3223 [>.............................] - ETA: 3s - loss: 1.6140 - acc: 0.4188

/Users/benchamberlain/anaconda/envs/tensorflow/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


3223/3223 [==============================] - 2s - loss: 1.6344 - acc: 0.3605     
Epoch 2/3
3223/3223 [==============================] - 2s - loss: 1.5791 - acc: 0.3739     
Epoch 3/3
3223/3223 [==============================] - 2s - loss: 1.5263 - acc: 0.3919     
t2
3226/3226 [==============================] - 1s     
t1
Epoch 1/3
 160/3226 [>.............................] - ETA: 3s - loss: 1.5924 - acc: 0.3812

/Users/benchamberlain/anaconda/envs/tensorflow/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


3226/3226 [==============================] - 2s - loss: 1.5552 - acc: 0.3909     
Epoch 2/3
3226/3226 [==============================] - 2s - loss: 1.4860 - acc: 0.4076     
Epoch 3/3
3226/3226 [==============================] - 1s - loss: 1.4234 - acc: 0.4392     
t2
3200/3223 [============================>.] - ETA: 0smacro
0.243415767372
micro
0.41076135835
all
[ 0.45235487  0.02588235  0.53511888  0.2352132   0.01149425  0.20043103]
